language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install ant
install:
  - pip install -r requirements.txt
script:
  - set -e
  - ./downloadRepos.py urls.txt "tokenizers/file-level/tokenizer-sample-input"
  - ./downloadRepos.py urls.txt "tokenizers/block-level/tokenizer-sample-input"
  - cd ..
  - mkdir test
  - mkdir test/t1
  - cp SourcererCC/ test/t1/ -r
  - cd test/t1/SourcererCC/
  - ./runSourcererCC-BlocksMode.sh | while read line; do printf "\e[32m[BlocksMode.sh] \e[0m$line\n"; done
  - sort -o results.pairs results.pairs
  - cat results.pairs
  - cd ../../..
  - mkdir test/t2
  - cp SourcererCC/ test/t2/ -r
  - cd test/t2/SourcererCC/
  - ./runSourcererCC-FilesMode.sh | while read line; do printf "\e[32m[FilesMode.sh] \e[0m$line\n"; done
  - sort -o results.pairs results.pairs
  - cat results.pairs
  - cd tokenizers/file-level
  - python tokenizers/file-level/utils/get_source_from_tokens.py --statsFiles=./tokenizers/file-level/files_stats --tokensFiles=./tokenizers/file-level/files_tokens
notifications:
  email:
    recipients:
      - poletansky@gmail.com
    on_success: never
    on_failure: always
