language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install ant tree
install:
  - pip install javalang
script:
  - cd ..
  - cp SourcererCC/test.sh .
  - ./test.sh
notifications:
  email:
    recipients:
      - poletansky@gmail.com
    on_success: never
    on_failure: always
