language: python
script:
  - sudo pip install javalang
  - sudo apt-get install ant
  - cd ..
  - cp SourcererCC/test.sh .
  - sudo ./test.sh
  - cat test/t1/rprtr258-SourcererCC-copy/clone-detector/Log_init.*
