language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install ant
  - pip3 install pylint
install:
  - pip3 install -r requirements.txt
script:
  - pylint *.py
  - pylint tokenizers/*/*.py
  - pylint clone-detector/*.py
  - python -m unittest
notifications:
  email:
    recipients:
      - poletansky@gmail.com
    on_success: never
    on_failure: always
