language: python
script:
  - sudo pip install javalang
  - sudo apt-get install ant
  - cd ..
  - cat test/t1/rprtr258-SourcererCC-copy/clone-detector/Log_init.*
  - mkdir test
  - cp SourcererCC/ test/rprtr258-SourcererCC-copy/ -r
  - cd test
  - mkdir t1 t2
  - cp rprtr258-SourcererCC-copy/ t1/ -r
  - cp rprtr258-SourcererCC-copy/ t2/ -r
  - mkdir ./t1/rprtr258-SourcererCC-copy/clone-detector/input/
  - mkdir ./t1/rprtr258-SourcererCC-copy/clone-detector/input/dataset/
  - mkdir ./t2/rprtr258-SourcererCC-copy/clone-detector/input/
  - mkdir ./t2/rprtr258-SourcererCC-copy/clone-detector/input/dataset/
  - cd ./t1/rprtr258-SourcererCC-copy/
  - ./runSourcererCC-BlocksMode.sh >../../blocks.out
  - echo "Blocks mode:"
  - cat results.pairs
  - cd ../../t2/rprtr258-SourcererCC-copy/
  - ./runSourcererCC-FilesMode.sh >../../files.out
  - echo "Files mode:"
  - cat results.pairs
