language: python
script:
  - sudo pip install javalang
  - sudo apt-get install ant
  - mkdir tmp
  - cp test.sh tmp
  - cd tmp
  - git clone https://github.com/rprtr258/SourcererCC
  - sudo ./test.sh
